### ISSUE TITLE
Error: undefined reference

### ISSUE THREAD

**Issue by derrick-xwp** [TobiasRp/mray#2]
Dear author, 

Do you know how to solve following issues?

[100%] Linking CXX executable mray
libmray_LIB.so: undefined reference to `nc_get_var_ubyte'
libmray_LIB.so: undefined reference to `nc_inq_dimid'
libmray_LIB.so: undefined reference to `nc_open'
libmray_LIB.so: undefined reference to `nc_inq_dimlen'
libmray_LIB.so: undefined reference to `nc_close'
libmray_LIB.so: undefined reference to `nc_get_att_float'
libmray_LIB.so: undefined reference to `nc_get_vara_ubyte'
libmray_LIB.so: undefined reference to `nc_get_vara_float'
libmray_LIB.so: undefined reference to `nc_inq_varid'
libmray_LIB.so: undefined reference to `nc_strerror'
libmray_LIB.so: undefined reference to `nc_inq_vartype'
libmray_LIB.so: undefined reference to `nc_get_var_float'
collect2: error: ld returned 1 exit status

**Comment by TobiasRp** [comment]
Hi, it seems that libnetcdf is not correctly installed.
